apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cx7l6c5gv-python
  janus-idp.io/tekton: cx7l6c5gv-python
  backstage.io/kubernetes-id: cx7l6c5gv-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cx7l6c5gv-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
