apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cx7l6c5gv-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cx7l6c5gv-python 
  name: cx7l6c5gv-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cx7l6c5gv-python 
